In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from pathlib import Path
pdb = "7lak"

outdir = Path(f"nm_displacement_fit_results/{pdb}/replica_0_max_displacement")

cum = pd.read_csv(outdir / "cumulative_first_modes_fit_summary.csv")
cum

,n_modes,mode_array_start,mode_array_stop_exclusive,first_bio3d_mode_number,last_bio3d_mode_number,cosine_overlap,abs_cosine_overlap,rms_error_nm
0,2,0,2,7,8,0.251153,0.251153,1.508267
1,3,0,3,7,9,0.253705,0.253705,1.507230
2,4,0,4,7,10,0.271382,0.271382,1.499735
3,5,0,5,7,11,0.724711,0.724711,1.073690
4,10,0,10,7,16,0.984775,0.984775,0.270869

In [3]:
import json

with open(outdir / "target_selection.json", "r") as f:
    target = json.load(f)

target

{'selected_frame_mode': 'max_displacement',
 'max_displacement_global_frame': 3792,
 'max_displacement_rms_nm': 0.4877791702747345,
 'max_displacement_xtc': '/work001/misc/bekker/kakC/dynamicsdb/raw/4/7lak/validation/0/prod.part0001.xtc',
 'max_displacement_local_frame_in_chunk': 92,
 'n_frames_scanned': 10001}

In [4]:
summary = pd.read_csv(outdir / "run_summary.csv")
summary.T

                                                                                       0
pdb                                                                                 7lak
replica                                                                                0
frame                                                                                 -1
target_mode                                                             max-displacement
n_protein_heavy_atoms                                                                999
expected_dof                                                                        2997
n_modes_keep                                                                          20
top_n_atoms                                                                           20
fit_start_array_index                                                                  0
fit_stop_array_index_exclusive                                                        20
mode_number_offset                                                                     7
best_single_mode_array_index                                                          19
best_single_bio3d_mode_number                                                         26
best_single_q_nm                                                               64.821166
best_single_cosine_overlap                                                      0.876853
combination_cosine_overlap                                                      0.993197
combination_rms_error_nm                                                        0.181448
selected_frame_mode                                                     max_displacement
max_displacement_global_frame                                                       3792
max_displacement_rms_nm                                                         0.487779
max_displacement_xtc                   /work001/misc/bekker/kakC/dynamicsdb/raw/4/7la...
max_displacement_local_frame_in_chunk                                                 92
n_frames_scanned                                                                   10001